#! /usr/bin/env bash

#
#  ██
# ░██              ██████
# ░██       ██████░██░░░██ ███     ██ ██████████
# ░██████  ██░░░░ ░██  ░██░░██  █ ░██░░██░░██░░██
# ░██░░░██░░█████ ░██████  ░██ ███░██ ░██ ░██ ░██
# ░██  ░██ ░░░░░██░██░░░   ░████░████ ░██ ░██ ░██
# ░██████  ██████ ░██      ███░ ░░███ ███ ░██ ░██
# ░░░░░   ░░░░░░  ░░      ░░░    ░░░ ░░░  ░░  ░░
#

###################################
#########     Startup      ########
###################################

# Make sure sxhkd is always running
while :; do
    if pgrep -x sxhkd > /dev/null; then
        true
    else
        sxhkd &
    fi
    sleep 5
done &

#/home/mehesares/.screenlayout/screenres.sh &
nitrogen --restore &
/home/mehesares/.config/polybar/launch.sh &
nm-applet &
flameshot &
killall -q redshift & && redshift &
xfce4-clipman &
xfce4-power-manager &
picom --experimental-backends &
dunst &

###################################
########     Workspaces    ########
###################################

bspc monitor LVDS-1 -d 1 2 3 4 5

#external_monitor=HDMI-1
#if [[ $(xrandr -q | grep "$external_monitor connected") ]]; then
#        bspc monitor HDMI-1 -d 1 2 3 4 5
#fi

###################################
#####     Window Settings     #####
###################################

bspc config border_radius               8
bspc config border_width                2

bspc config window_gap                  10

bspc config top_padding                 22
bspc config bottom_padding              0
bspc config left_padding                0
bspc config right_padding               0

bspc config top_monocle_padding         0
bspc config right_monocle_padding       0
bspc config left_monocle_padding        0
bspc config bottom_monocle_padding      0

#bspc config external_rules_command "$HOME/.config/bspwm/external_rules.sh"

bspc config pointer_follows_monitor     true
bspc config focus_follows_pointer       true
bspc config click_to_focus              true
bspc config focus_by_distance           true
bspc config history_aware_focus         true

bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config single_monocle              false

bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true
bspc config merge_overlapping_monitors  true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

###################################
#####    Application Rules    #####
###################################

# remove all rules first
bspc rule -r *:*

# Use command "xprop | grep WM_CLASS" to find the name of the application to be entered below
bspc rule -a Brave-browser      follow=on
bspc rule -a Gimp               follow=on
bspc rule -a Kupfer.py          focus=on
bspc rule -a Screenkey          manage=off
bspc rule -a Nitrogen           state=floating
bspc rule -a Pavucontrol        state=floating
bspc rule -a GParted            state=floating

###################################
#####      Border Colours     #####
###################################

bspc config focused_border_color    "#6272A4"
bspc config normal_border_color     "#6272A4"
bspc config active_border_color     "#6272A4"
bspc config presel_feedback_color   "#6272A4"
bspc config urgent_border_color     "#dd2727"