#! /usr/bin/env bash

#
#  ██
# ░██              ██████
# ░██       ██████░██░░░██ ███     ██ ██████████
# ░██████  ██░░░░ ░██  ░██░░██  █ ░██░░██░░██░░██
# ░██░░░██░░█████ ░██████  ░██ ███░██ ░██ ░██ ░██
# ░██  ░██ ░░░░░██░██░░░   ░████░████ ░██ ░██ ░██
# ░██████  ██████ ░██      ███░ ░░███ ███ ░██ ░██
# ░░░░░   ░░░░░░  ░░      ░░░    ░░░ ░░░  ░░  ░░
#

###################################
#########     Startup      ########
###################################

# Make sure sxhkd is always running

while :; do
    if pgrep -x sxhkd > /dev/null; then
        true
    else
        sxhkd &
    fi
    sleep 5
done &

# Kill if already running
killall -9 sxhkd dunst ksuperkey xfce4-power-manager

#/home/mehesares/.screenlayout/screenres.sh &
#/home/mehesares/.config/polybar/launch.sh &
#feh --no-fehbg --bg-fill /home/mehesares/Pictures/catgradient1.png &
nitrogen --restore &
polybar -r -c /home/mehesares/bspwm-polybar/config.ini &
nm-applet &
flameshot &
xfce4-clipman &
tint2 &
xfce4-power-manager &
picom --experimental-backends &
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
dunst &
notify-send "Welcome back Aryan!"

#Use the mod key to launch rofi
ksuperkey -e 'Super_L=Alt_L|F1'

# Fix cursor
xsetroot -cursor_name left_ptr

###################################
########     Workspaces    ########
###################################

#bspc monitor LVDS-1 -d 1 2 3 4 5 6 7 8

#external_monitor=HDMI-1

#if [[ $(xrandr -q | grep "$external_monitor connected") ]]; then
#        bspc monitor HDMI-1 -d 1 2 3 4 5 6
#fi

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		#bspc monitor ${monitor} -n "$name" -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII'
		bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' ''
		let name++
	done
}
workspaces

###################################
#####     Window Settings     #####
###################################

bspc config border_radius               10
bspc config border_width                2

bspc config window_gap                  8

bspc config top_padding                 36
bspc config bottom_padding              0
bspc config left_padding                0
bspc config right_padding               0

bspc config top_monocle_padding         0
bspc config right_monocle_padding       0
bspc config left_monocle_padding        0
bspc config bottom_monocle_padding      0

bspc config pointer_follows_monitor     true
bspc config focus_follows_pointer       true
bspc config click_to_focus              false
#bspc config focus_by_distance           true
#bspc config history_aware_focus         true

bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config single_monocle              false

bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true
bspc config merge_overlapping_monitors  true

bspc config pointer_modifier    mod4
bspc config pointer_action1     move
bspc config pointer_action2     resize_side
bspc config pointer_action3     resize_corner

###################################
#####    Application Rules    #####
###################################

# remove all rules first
bspc rule -r *:*

# Use command "xprop | grep WM_CLASS" to find the name of the application to be entered below
bspc rule -a Brave-browser      follow=on
bspc rule -a Kupfer.py          focus=on
bspc rule -a Screenkey          manage=off
bspc rule -a Nitrogen           state=floating
bspc rule -a Pavucontrol        state=floating
bspc rule -a GParted            state=floating
bspc rule -a Guake              state=floating
bspc rule -a Conky              state=floating      manage=off

###################################
#####      Border Colours     #####
###################################

bspc config focused_border_color    "#ddb6f2"
bspc config normal_border_color     "#6272A4"
bspc config active_border_color     "#6272A4"
bspc config urgent_border_color     "#dd2727"
