#!/bin/sh

headvol() {
  amixer sget Headphone | grep 'Left:' | cut -d\  -f7 | tr -d '[%]'
}

mastervol() {
  amixer get Master | awk '$0~/%/{print $4}' | tr -d '[%]'
}

micvol() {
  amixer sget 'Internal Mic Boost' | grep 'Left:' | cut -d\  -f6 | tr -d '[%]'
}

"$@"